package com.flowbudget.app
import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import java.text.NumberFormat
import java.util.Locale

val Emerald=Color(0xFF0A7A5A);val Navy=Color(0xFF102A43);val Soft=Color(0xFFF3F7F5);val Gold=Color(0xFFE6A817)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme(colorScheme=lightColorScheme(primary=Emerald,secondary=Gold,surface=Color.White,background=Soft)){FlowBudgetApp(FinanceStore(this))}}}}
@Composable fun FlowBudgetApp(store:FinanceStore){var tab by remember{mutableIntStateOf(0)};var refresh by remember{mutableIntStateOf(0)};refresh;val tx=store.transactions();val inc=tx.filter{it.type==TxType.INCOME}.sumOf{it.amount};val exp=tx.filter{it.type==TxType.EXPENSE}.sumOf{it.amount};Scaffold(containerColor=Soft,bottomBar={NavigationBar(containerColor=Color.White){listOf("Home" to Icons.Default.Home,"Activity" to Icons.Default.ReceiptLong,"Banks" to Icons.Default.AccountBalance,"Budget" to Icons.Default.PieChart,"Plus" to Icons.Default.Star).forEachIndexed{i,p->NavigationBarItem(tab==i,{tab=i},{Icon(p.second,null)},label={Text(p.first)})}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when(tab){0->Dashboard(store,inc,exp,tx);1->Transactions(store,tx){refresh++};2->Banks(store){refresh++};3->Budget(store,exp){refresh++};else->Premium(store,tx){refresh++}}}}}
fun money(v:Double)=NumberFormat.getCurrencyInstance(Locale("en","NG")).format(v)
@Composable fun Title(t:String,s:String){Column(Modifier.padding(bottom=18.dp)){Text(t,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold,color=Navy);Text(s,color=Color.Gray)}}
@Composable fun Dashboard(store:FinanceStore,inc:Double,exp:Double,tx:List<Transaction>){LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("Good day",color=Color.Gray);Text("Flow Budget",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=Navy)};Surface(shape=RoundedCornerShape(50),color=if(store.premium())Gold else Emerald){Text(if(store.premium())" PLUS " else " BASIC ",Modifier.padding(8.dp),color=Color.White,fontWeight=FontWeight.Bold)}};Spacer(Modifier.height(18.dp));Box(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Navy,Emerald)),RoundedCornerShape(26.dp)).padding(24.dp)){Column{Text("TOTAL BALANCE",color=Color.White.copy(.75f));Text(money(inc-exp),style=MaterialTheme.typography.headlineLarge,color=Color.White,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(20.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Metric("Income",money(inc),Color.White);Metric("Spent",money(exp),Color.White)}}};Spacer(Modifier.height(20.dp));Text("Monthly plan",fontWeight=FontWeight.Bold,color=Navy);Spacer(Modifier.height(8.dp));ElevatedCard(shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp)){val b=store.budget();LinearProgressIndicator(progress={if(b<=0)0f else (exp/b).toFloat().coerceIn(0f,1f)},Modifier.fillMaxWidth().height(9.dp));Spacer(Modifier.height(10.dp));Text(money(exp)+" spent of "+money(b));Text(money((b-exp).coerceAtLeast(0.0))+" remaining",color=Emerald,fontWeight=FontWeight.SemiBold)}};Spacer(Modifier.height(22.dp));Text("Recent transactions",fontWeight=FontWeight.Bold,color=Navy)};items(tx.take(6)){TxRow(it)}}}
@Composable fun Metric(a:String,b:String,c:Color){Column{Text(a,color=c.copy(.7f));Text(b,color=c,fontWeight=FontWeight.Bold)}}
@Composable fun TxRow(t:Transaction){Card(Modifier.fillMaxWidth().padding(vertical=5.dp),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){ListItem(colors=ListItemDefaults.colors(containerColor=Color.Transparent),leadingContent={Surface(shape=RoundedCornerShape(12.dp),color=if(t.type==TxType.INCOME)Color(0xFFE5F6EF) else Color(0xFFFFECE8)){Icon(if(t.type==TxType.INCOME)Icons.Default.SouthWest else Icons.Default.NorthEast,null,Modifier.padding(10.dp),tint=if(t.type==TxType.INCOME)Emerald else Color(0xFFC84B31))}},headlineContent={Text(t.category,fontWeight=FontWeight.Bold)},supportingContent={Text(t.source)},trailingContent={Text((if(t.type==TxType.INCOME)"+ " else "- ")+money(t.amount),fontWeight=FontWeight.Bold,color=if(t.type==TxType.INCOME)Emerald else Navy)})}}
@Composable fun Transactions(store:FinanceStore,tx:List<Transaction>,changed:()->Unit){var show by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().padding(18.dp)){Title("Activity","Everything moving in and out");Button({show=true},shape=RoundedCornerShape(14.dp)){Icon(Icons.Default.Add,null);Text(" Add transaction")};Spacer(Modifier.height(10.dp));LazyColumn{items(tx){TxRow(it)}}};if(show)AddDialog({show=false}){store.add(it);show=false;changed()}}
@Composable fun AddDialog(close:()->Unit,add:(Transaction)->Unit){var a by remember{mutableStateOf("")};var n by remember{mutableStateOf("")};var inc by remember{mutableStateOf(false)};AlertDialog(onDismissRequest=close,title={Text("Add transaction")},text={Column{OutlinedTextField(a,{a=it},label={Text("Amount")});OutlinedTextField(n,{n=it},label={Text("Description")});Row(verticalAlignment=Alignment.CenterVertically){Switch(inc,{inc=it});Text(if(inc)" Income" else " Expense")}}},confirmButton={Button({a.toDoubleOrNull()?.let{add(Transaction(type=if(inc)TxType.INCOME else TxType.EXPENSE,amount=it,category=if(inc)"Income" else "Other",note=n))}}){Text("Save")}},dismissButton={TextButton(close){Text("Cancel")}})}
@Composable fun Banks(store:FinanceStore,changed:()->Unit){val ctx=LocalContext.current;var discovered by remember{mutableStateOf(emptyList<SmsSender>())};var status by remember{mutableStateOf("Grant access, then scan your messages.")};fun scan(){runCatching{discovered=SmsImporter.discover(ctx);status=if(discovered.isEmpty())"No financial SMS senders detected yet." else "Found "+discovered.size+" possible financial senders."}.onFailure{status="SMS access is not available."}};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){p->if(p[Manifest.permission.READ_SMS]==true)scan()};LaunchedEffect(Unit){if(ContextCompat.checkSelfPermission(ctx,Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED)scan()};LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Title("Bank connections","Your SMS stays on this phone");ElevatedCard(shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Icon(Icons.Default.Security,null,tint=Emerald);Text("Private SMS import",fontWeight=FontWeight.Bold);Text("Flow Budget scans transaction alerts locally. Only senders you approve are imported.");Spacer(Modifier.height(12.dp));Button({launcher.launch(arrayOf(Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS))}){Text("Grant SMS access")};OutlinedButton({scan()}){Text("Scan existing SMS")};Text(status,color=Color.Gray)}};Spacer(Modifier.height(18.dp));Text("Detected senders",fontWeight=FontWeight.Bold,color=Navy)};items(discovered){s->val allowed=store.allowedSenders().contains(s.address.uppercase());Card(Modifier.fillMaxWidth().padding(vertical=5.dp),shape=RoundedCornerShape(18.dp)){ListItem(headlineContent={Text(s.address,fontWeight=FontWeight.Bold)},supportingContent={Text(s.count.toString()+" financial-looking messages\n"+s.sample)},trailingContent={Switch(allowed,{on->if(on)store.addSender(s.address)else store.removeSender(s.address);changed()})})}};item{if(store.allowedSenders().isNotEmpty()){Spacer(Modifier.height(14.dp));Button({val n=SmsImporter.importAllowed(ctx,store);status="$n transactions imported";changed()},Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.Download,null);Text(" Import from approved banks")}}}}}
@Composable fun Budget(store:FinanceStore,exp:Double,changed:()->Unit){var v by remember{mutableStateOf(store.budget().toLong().toString())};Column(Modifier.padding(18.dp)){Title("Monthly budget","Give every naira a purpose");ElevatedCard(shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){OutlinedTextField(v,{v=it},label={Text("Spending limit (₦)")});Spacer(Modifier.height(10.dp));Button({v.toDoubleOrNull()?.let{store.setBudget(it);changed()}},shape=RoundedCornerShape(14.dp)){Text("Save budget")};Spacer(Modifier.height(20.dp));Text("Spent  "+money(exp));Text("Available  "+money((store.budget()-exp).coerceAtLeast(0.0)),fontWeight=FontWeight.Bold,color=Emerald)}}}}
@Composable fun Premium(store:FinanceStore,tx:List<Transaction>,changed:()->Unit){val p=store.premium();val biggest=tx.filter{it.type==TxType.EXPENSE}.maxByOrNull{it.amount};LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Title(if(p)"Flow Budget Plus ✦" else "Flow Budget Plus","Unlock smarter money tools");Card(colors=CardDefaults.cardColors(containerColor=if(p)Color(0xFFFFF4D6) else Color.White),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(22.dp)){Icon(Icons.Default.WorkspacePremium,null,tint=Gold,modifier=Modifier.size(38.dp));Text(if(p)"Premium test mode is ACTIVE" else "Try the complete experience",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,color=Navy);Text(if(p)"Advanced insights and premium cards below are now unlocked." else "Enable test mode to preview features before billing is connected.");Spacer(Modifier.height(14.dp));Button({store.setPremium(!p);changed()},colors=ButtonDefaults.buttonColors(containerColor=if(p)Navy else Gold)){Text(if(p)"Return to Basic" else "Activate Premium test mode")}}};Spacer(Modifier.height(18.dp));if(p){Text("Premium insights",fontWeight=FontWeight.Bold,color=Navy);PremiumCard("Smart spending insight",if(biggest!=null)"Your largest recorded expense is "+money(biggest.amount)+" in "+biggest.category+"." else "Import transactions to generate insights.",Icons.Default.AutoGraph);PremiumCard("Multiple accounts","Separate bank accounts, cash and savings in the upcoming account manager.",Icons.Default.AccountBalanceWallet);PremiumCard("Reports & export","Advanced monthly reports and CSV/PDF export are unlocked for development.",Icons.Default.Assessment)}else{Text("Premium includes",fontWeight=FontWeight.Bold,color=Navy);Text("Advanced analytics • multiple accounts • unlimited goals • recurring transactions • reports & export",Modifier.padding(top=10.dp))}}}}
@Composable fun PremiumCard(t:String,s:String,i:androidx.compose.ui.graphics.vector.ImageVector){ElevatedCard(Modifier.fillMaxWidth().padding(vertical=6.dp),shape=RoundedCornerShape(20.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=Emerald,modifier=Modifier.size(30.dp));Spacer(Modifier.width(14.dp));Column{Text(t,fontWeight=FontWeight.Bold);Text(s,color=Color.Gray)}}}}
