package com.flowbudget.app
import java.text.SimpleDateFormat
import java.util.*
data class Insight(val title:String,val body:String)
object SmartAnalyzer{
 fun filter(tx:List<Transaction>,bank:String,period:String,month:Int,year:Int):List<Transaction>{val now=Calendar.getInstance();return tx.filter{t->val c=Calendar.getInstance().apply{timeInMillis=t.timestamp};val bankOk=bank=="All accounts"||t.bank+" "+t.account==bank;val timeOk=when(period){"This month"->c.get(Calendar.MONTH)==now.get(Calendar.MONTH)&&c.get(Calendar.YEAR)==now.get(Calendar.YEAR);"Selected month"->c.get(Calendar.MONTH)==month&&c.get(Calendar.YEAR)==year;"This year"->c.get(Calendar.YEAR)==year;else->true};bankOk&&timeOk}}
 fun insights(tx:List<Transaction>,budget:Double):List<Insight>{if(tx.isEmpty())return listOf(Insight("AI-style analysis","Import more transactions to build useful spending intelligence."));val expenses=tx.filter{it.type==TxType.EXPENSE};val income=tx.filter{it.type==TxType.INCOME}.sumOf{it.amount};val spent=expenses.sumOf{it.amount};val top=expenses.groupBy{it.category}.mapValues{it.value.sumOf{x->x.amount}}.maxByOrNull{it.value};val avg=if(expenses.isEmpty())0.0 else spent/expenses.size;val save=income-spent;val ratio=if(income>0)spent/income else 0.0;val result=mutableListOf<Insight>();result+=Insight("Cash-flow health",if(income>0)"You spent "+pct(ratio)+" of recorded income and retained "+money(save)+" in this view." else "No income was detected in this view, so savings rate cannot yet be calculated.");if(top!=null)result+=Insight("Top spending category",top.key+" is highest at "+money(top.value)+". Consider setting a category cap if this is discretionary.");result+=Insight("Typical expense","Your average recorded debit is "+money(avg)+". Transactions far above this deserve a quick review.");val suggested=when{income>0->(income*.70).coerceAtLeast(spent*.9);spent>0->spent*.95;else->budget};result+=Insight("Suggested monthly budget","Based on the current pattern, a starting spending ceiling is "+money(suggested)+". Adjust it for bills or irregular expenses the SMS history may not capture.");return result}
 private fun pct(v:Double)=String.format(Locale.US,"%.0f%%",v*100)
 fun label(t:Long)=SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(Date(t))
}
